// Assignment 관련 에러 코드 정의
export enum AssignmentErrorCode {
  ASSIGNMENT_NOT_FOUND = 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_NOT_PUBLISHED = 'ASSIGNMENT_NOT_PUBLISHED',
  ASSIGNMENT_CLOSED = 'ASSMENT_CLOSED',
  USER_NOT_ENROLLED = 'USER_NOT_ENROLLED',
  SUBMISSION_NOT_FOUND = 'SUBMISSION_NOT_FOUND',
  INVALID_SUBMISSION_DATA = 'INVALID_SUBMISSION_DATA',
  SUBMISSION_NOT_ALLOWED = 'SUBMISSION_NOT_ALLOWED',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  SUBMISSIONS_FETCH_ERROR = 'SUBMISSIONS_FETCH_ERROR',
  INVALID_GRADE = 'INVALID_GRADE',
  GRADE_SUBMISSION_ERROR = 'GRADE_SUBMISSION_ERROR',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  ASSIGNMENT_ALREADY_PUBLISHED = 'ASSIGNMENT_ALREADY_PUBLISHED',
  ASSIGNMENT_ALREADY_CLOSED = 'ASSIGNMENT_ALREADY_CLOSED',
  INVALID_ASSIGNMENT_DATA = 'INVALID_ASSIGNMENT_DATA',
}

export class AssignmentError extends Error {
  constructor(
    public code: AssignmentErrorCode,
    message: string,
    public status: number = 400
  ) {
    super(message);
    this.name = 'AssignmentError';
  }
}